price_intelligence:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: lyrical-lyceum-499123-c2
      dataset: price_intelligence
      threads: 4
      timeout_seconds: 300